name: ERCnet_py3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.7
  - pandas
  - biopython
  - joblib
  - scipy
  - mafft
  - gblocks
  - raxml
  - treerecs
  - r-base=4.1.2
  - r-stringr
  - r-ape=5.6
  - r-phytools
  - bioconda::newick_utils
